index:
	gcc -Wall -pedantic -g -o indexdb index-db.c index-tools.c util.c

queryBST:
	gcc -Wall -pedantic -g -o queryBST query-with-doclen-BST.c query-tools-BST.c util.c -lm

queryHash:
	gcc -Wall -pedantic -g -o queryHash query-with-doclen-Hash.c query-tools-Hash.c util.c -lm
